platform: Any CPU
configuration: Release

image: Visual Studio 2017

build:
  parallel: true
  project: RichardSzalay.MockHttp.sln

before_build:
  - nuget restore
  
after_build:
  - nuget pack RichardSzalay.MockHttp.nuspec -version %APPVEYOR_BUILD_VERSION%-pre
  - appveyor PushArtifact RichardSzalay.MockHttp.%APPVEYOR_BUILD_VERSION%-pre.nupkg
